Countrylist = {
    "US": "美国",
    "United Kingdom": "英国",
    "Italy": "意大利",
    "Brazil": "巴西",
    "France": "法国",
    "Spain": "西班牙",
    "Mexico": "墨西哥",
    "Belgium": "比利时",
    "Germany": "德国",
    "Iran": "伊朗",
    "Canada": "加拿大",
    "India": "印度",
    "Netherlands": "荷兰",
    "Russia": "俄罗斯",
    "Peru": "秘鲁",
    "China": "中国",
    "Turkey": "土耳其",
    "Sweden": "瑞典",
    "Ecuador": "厄瓜多尔",
    "Switzerland": "瑞士",
    "Pakistan": "巴基斯坦",
    "Indonesia": "印度尼西亚",
    "Ireland": "爱尔兰",
    "Portugal": "葡萄牙",
    "Romania": "罗马尼亚",
    "Chile": "智利",
    "Poland": "波兰",
    "Colombia": "哥伦比亚",
    "Egypt": "埃及",
    "Philippines": "菲律宾",
    "Japan": "日本",
    "South Africa": "南非",
    "Bangladesh": "孟加拉国",
    "Ukraine": "乌克兰",
    "Algeria": "阿尔及利亚",
    "Austria": "奥地利",
    "Argentina": "阿根廷",
    "Denmark": "丹麦",
    "Saudi Arabia": "沙特阿拉伯",
    "Hungary": "匈牙利",
    "Dominican Republic": "多明尼加共和国",
    "Bolivia": "玻利维亚",
    "Panama": "巴拿马",
    "Czechia": "捷克",
    "Finland": "芬兰",
    "Nigeria": "尼日利亚",
    "Moldova": "摩尔多瓦",
    "Sudan": "苏丹",
    "Afghanistan": "阿富汗",
    "Israel": "以色列",
    "Korea, South": "韩国",
    "United Arab Emirates": "阿拉伯联合酋长国",
    "Iraq": "伊拉克",
    "Belarus": "白俄罗斯",
    "Serbia": "塞尔维亚",
    "Norway": "挪威",
    "Honduras": "洪都拉斯",
    "Kuwait": "科威特",
    "Morocco": "摩洛哥",
    "Cameroon": "喀麦隆",
    "Greece": "希腊",
    "Armenia": "亚美尼亚",
    "Bosnia and Herzegovina": "波黑",
    "Bulgaria": "保加利亚",
    "North Macedonia": '北马其顿',
    "Guatemala": "危地马拉",
    "Malaysia": "马来西亚",
    "Luxembourg": "卢森堡",
    "Slovenia": "斯洛文尼亚",
    "Croatia": "克罗地亚",
    "Australia": "澳大利亚",
    "Yemen": "也门",
    "Cuba": "古巴",
    "Mali": "马里",
    "Somalia": "索马里",
    "Congo (Kinshasa)": "刚果金",
    "Azerbaijan": "阿塞拜疆",
    "Kenya": "肯尼亚",
    "Lithuania": "立陶宛",
    "Estonia": "爱沙尼亚",
    "Oman": "阿曼",
    "Chad": "乍得",
    "Niger": "尼日尔",
    "Thailand": "泰国",
    "Burkina Faso": "布基纳法索",
    "Andorra": "安道尔",
    "El Salvador": "萨尔瓦多",
    "Haiti": "海地",
    "Tunisia": "突尼斯",
    "Kazakhstan": "哈萨克斯坦",
    "Tajikistan": "塔吉克斯坦",
    "Sierra Leone": "塞拉利昂",
    "Nicaragua": "尼加拉瓜",
    "Qatar": "卡塔尔",
    "Senegal": "塞内加尔",
    "San Marino": "圣马力诺",
    "Ghana": "加纳",
    "Cote d'Ivoire": "科特迪瓦",
    "Mauritania": "毛里塔尼亚",
    "Albania": "阿尔巴尼亚",
    "Kosovo": "科索沃",
    "Liberia": "利比里亚",
    "Slovakia": "斯洛伐克",
    "Lebanon": "黎巴嫩",
    "Djibouti": "吉布提",
    "Latvia": "拉脱维亚",
    "Singapore": "新加坡",
    "Guinea": "几内亚",
    "Uruguay": "乌拉圭",
    "New Zealand": "新西兰",
    "Tanzania": "坦桑尼亚",
    "Bahrain": "巴林",
    "Congo (Brazzaville)": "刚果（布拉柴维尔）",
    "Gabon": "加蓬",
    "Kyrgyzstan": "吉尔吉斯斯坦",
    "Venezuela": "委内瑞拉",
    "Cyprus": "塞浦路斯",
    "Ethiopia": "埃塞俄比亚",
    "Uzbekistan": "乌兹别克斯坦",
    "Diamond Princess": "钻石公主号邮轮",
    "Georgia": "乔治亚",
    "Togo": "多哥",
    "Equatorial Guinea": "赤道几内亚",
    "Guyana": "圭亚那",
    "Sao Tome and Principe": "圣多美和普林西比",
    "Bahamas": "巴哈马",
    "Paraguay": "巴拉圭",
    "Sri Lanka": "斯里兰卡",
    "Iceland": "冰岛",
    "Costa Rica": "哥斯达黎加",
    "Jamaica": "牙买加",
    "Mauritius": "毛里求斯",
    "South Sudan": "南苏丹",
    "Jordan": "约旦",
    "Malta": "马耳他",
    "Montenegro": "黑山",
    "Nepal": "尼泊尔",
    "Guinea-Bissau": "几内亚比绍共和国",
    "Trinidad and Tobago": "特立尼达和多巴哥共和国",
    "Barbados": "巴巴多斯",
    "Maldives": "马尔代夫",
    "Taiwan*": "中国台湾",
    "Zambia": "赞比亚",
    "Burma": "缅甸",
    "Madagascar": "马达加斯加",
    "Syria": "叙利亚",
    "Cabo Verde": "佛得角",
    "Libya": "利比亚",
    "Angola": "安哥拉",
    "Central African Republic": "中非共和国",
    "Malawi": "马拉维",
    "Monaco": "摩纳哥",
    "Zimbabwe": "津巴布韦",
    "Antigua and Barbuda": "安提瓜和巴布达",
    "Benin": "贝宁",
    "Eswatini": "斯威士兰",
    "West Bank and Gaza": "约旦河西岸和加沙",
    "Belize": "伯利兹",
    "Brunei": "文莱",
    "Comoros": "科摩罗",
    "MS Zaandam": "尚丹号邮轮",
    "Mozambique": "莫桑比克",
    "Rwanda": "卢旺达",
    "Botswana": "博茨瓦纳",
    "Burundi": "布隆迪",
    "Gambia": "冈比亚",
    "Liechtenstein": "列支敦士登",
    "Suriname": "苏里南",
    "Western Sahara": "西撒哈拉"
}
